### PR TITLE
separate account creation from abstract creation

### PR DESCRIPTION
**Pull request by joelmccracken**
- do not show create account fields if user is logged in.
- if valid user is not either created or extracted from session, re-render
  submit page.

### CODE REVIEW

**Comment by joelmccracken** [comment]
Closes #56

**Comment by joelmccracken** [comment]
@bitemyapp I resolved the conflicts. The build errored, but I its OK.

**Comment by bitemyapp** [comment]
@joelmccracken This is great thank you! Just kicked it around on my machine and I like the way this works.

**Comment by joelmccracken** [comment]
Awesome!

**Pull request merged**
