### PR TITLE
Cfp dashboard

### PR DESCRIPTION
**Pull request by tdietert**
This PR accomplishes #13 

- [x] Adds CFP dashboard route `/conference/#Int64/cfp`, reachable by conference `Admin/Owner` only
- [x] Displays number of submitted abstracts and their details in table 

Notes:
- There are some merge conflict resolution artifacts (i did my best)
- All previously functionality tested

### CODE REVIEW

**Comment by joelmccracken** [comment]
I checked this out and built/ran it. Looks OK to me, but the output is not tabular, but in a list format.

**Comment by joelmccracken** [comment]
I could not submit an abstract on this branch because of the uniqueness constraint on an abstract's abstract_type. Not sure if this was a merge issue.

**Comment by bitemyapp** [comment]
>I could not submit an abstract on this branch because of the uniqueness constraint on an abstract's abstract_type. Not sure if this was a merge issue.

Sounds like a mistake. I'll take a look.

**Comment by tdietert** [comment]
The abstracts are not listed as tables because I couldn't get the row/columns CSS to work :confused: 
https://github.com/lorepub/moot/pull/58/files#diff-62fdf5fc4e2aa5a17a89ceec4d07cd82R179

Feel free to make a commit that displays this in tabular format.

**Comment by tdietert** [comment]
And good catch about the unique constraint-- that was indeed a mistake. I have corrected it now :+1:

**Comment by bitemyapp** [comment]
Thank you @tdietert!

**Pull request merged**
